# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class LoginWidget(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1007, 822)
        mainWindow.setStyleSheet("border-image: url(:/image/foto/statue.jpg);")
        self.verticalLayout = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginWidget = QtWidgets.QWidget(parent=mainWindow)
        self.loginWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.loginWidget.setMaximumSize(QtCore.QSize(600, 400))
        self.loginWidget.setSizeIncrement(QtCore.QSize(5, 5))
        self.loginWidget.setStyleSheet("QWidget{\n"
"    background: none;\n"
"    border-image: none;\n"
"    background-color: rgba(145, 145, 145, 155);\n"
"    border: 0px solid black;\n"
"    border-radius: 25px;\n"
"}")
        self.loginWidget.setObjectName("loginWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Register_label = QtWidgets.QLabel(parent=self.loginWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Register_label.setFont(font)
        self.Register_label.setStyleSheet("background-color: rgb();\n"
"border-image: none;\n"
"border: 0px solid black;\n"
"border-radius: 0px;")
        self.Register_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Register_label.setObjectName("Register_label")
        self.verticalLayout_2.addWidget(self.Register_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.usernameLE = QtWidgets.QLineEdit(parent=self.loginWidget)
        self.usernameLE.setMinimumSize(QtCore.QSize(300, 40))
        self.usernameLE.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.usernameLE.setFont(font)
        self.usernameLE.setStyleSheet("background: transparent;\n"
"border-bottom: 2px solid black;")
        self.usernameLE.setObjectName("usernameLE")
        self.verticalLayout_2.addWidget(self.usernameLE, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.passwordLE = QtWidgets.QLineEdit(parent=self.loginWidget)
        self.passwordLE.setMinimumSize(QtCore.QSize(300, 40))
        self.passwordLE.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLE.setFont(font)
        self.passwordLE.setStyleSheet("background: transparent;\n"
"border-bottom: 2px solid black;")
        self.passwordLE.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLE.setObjectName("passwordLE")
        self.verticalLayout_2.addWidget(self.passwordLE, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.start_btn = QtWidgets.QPushButton(parent=self.loginWidget)
        self.start_btn.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.start_btn.setFont(font)
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.start_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(232, 215, 195);\n"
"    border: 0px solid black;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.977, y1:0.489, x2:0.006, y2:0.5225, stop:0 rgba(92, 78, 59, 255), stop:1 rgba(212, 202, 188, 255));\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_2.addWidget(self.start_btn)
        self.kayit_giris = QtWidgets.QLabel(parent=self.loginWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.kayit_giris.setFont(font)
        self.kayit_giris.setStyleSheet("QLabel:hover {\n"
"    background-color: rgb(109, 109, 109);\n"
"    color: white;\n"
"}")
        self.kayit_giris.setObjectName("kayit_giris")
        self.verticalLayout_2.addWidget(self.kayit_giris)
        self.verticalLayout.addWidget(self.loginWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Form"))
        self.Register_label.setText(_translate("mainWindow", "Kayıt Ol"))
        self.usernameLE.setPlaceholderText(_translate("mainWindow", "Kullanıcı Girişi"))
        self.passwordLE.setPlaceholderText(_translate("mainWindow", "Şifre"))
        self.start_btn.setText(_translate("mainWindow", "Giriş"))
        self.kayit_giris.setText(_translate("mainWindow", "  Hesabınız yoksa Kayıt Oluşturunuz "))
