# Form implementation generated from reading ui file 'register1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class RegisterWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(966, 888)
        Form.setMinimumSize(QtCore.QSize(966, 888))
        Form.setStyleSheet("#Form{\n"
"    background-color: rgb(68, 64, 42);\n"
"    border-image: url(:/image/foto/themis heykeli.jpg);\n"
"}")
        self.back_label = QtWidgets.QLabel(parent=Form)
        self.back_label.setGeometry(QtCore.QRect(180, 50, 591, 761))
        self.back_label.setStyleSheet("#back_label{\n"
"    background: none;\n"
"    border-image: none;\n"
"    background-color: rgba(63, 63, 63, 155);\n"
"    border: 0px solid black;\n"
"    border-radius: 25px;\n"
"}")
        self.back_label.setText("")
        self.back_label.setObjectName("back_label")
        self.icon = QtWidgets.QLabel(parent=Form)
        self.icon.setGeometry(QtCore.QRect(400, 70, 141, 131))
        self.icon.setStyleSheet("border-image: url(:/image/foto/1.c.png);")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.register_nameLE = QtWidgets.QLabel(parent=Form)
        self.register_nameLE.setGeometry(QtCore.QRect(300, 220, 361, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.register_nameLE.setFont(font)
        self.register_nameLE.setStyleSheet("#register_nameLE{\n"
"background-color: rgb();\n"
"border-image: none;\n"
"color:white;\n"
"border: 0px solid black;\n"
"border-radius: 0px;}")
        self.register_nameLE.setObjectName("register_nameLE")
        self.passWordLE_2 = QtWidgets.QLineEdit(parent=Form)
        self.passWordLE_2.setGeometry(QtCore.QRect(330, 390, 300, 40))
        self.passWordLE_2.setMinimumSize(QtCore.QSize(300, 40))
        self.passWordLE_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.passWordLE_2.setFont(font)
        self.passWordLE_2.setStyleSheet("#passWordLE_2{\n"
"background: transparent;\n"
"color:white;\n"
"border-bottom: 2px solid black;}")
        self.passWordLE_2.setObjectName("passWordLE_2")
        self.officenameLE = QtWidgets.QLineEdit(parent=Form)
        self.officenameLE.setGeometry(QtCore.QRect(330, 460, 300, 40))
        self.officenameLE.setMinimumSize(QtCore.QSize(300, 40))
        self.officenameLE.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.officenameLE.setFont(font)
        self.officenameLE.setStyleSheet("#officenameLE{\n"
"background: transparent;\n"
"color:white;\n"
"border-bottom: 2px solid black;\n"
"}")
        self.officenameLE.setObjectName("officenameLE")
        self.officeNO = QtWidgets.QLineEdit(parent=Form)
        self.officeNO.setGeometry(QtCore.QRect(330, 530, 300, 40))
        self.officeNO.setMinimumSize(QtCore.QSize(300, 40))
        self.officeNO.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.officeNO.setFont(font)
        self.officeNO.setStyleSheet("#officeNO{\n"
"background: transparent;\n"
"border-bottom: 2px solid black;\n"
"color:white;\n"
"}")
        self.officeNO.setObjectName("officeNO")
        self.Reg_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Reg_pushButton.setGeometry(QtCore.QRect(230, 630, 500, 91))
        self.Reg_pushButton.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.Reg_pushButton.setFont(font)
        self.Reg_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Reg_pushButton.setStyleSheet("Reg_pushButton{\n"
"    background-color: rgb(68, 64, 42);\n"
"    border: 0px solid black;\n"
"    border-radius: 15px;\n"
"}\n"
"Reg_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.977, y1:0.489, x2:0.006, y2:0.5225, stop:0 rgba(89, 89, 25, 255), stop:1 rgba(145, 145, 141, 255));\n"
"}")
        self.Reg_pushButton.setObjectName("Reg_pushButton")
        self.usernameLE = QtWidgets.QLineEdit(parent=Form)
        self.usernameLE.setGeometry(QtCore.QRect(330, 320, 300, 40))
        self.usernameLE.setMinimumSize(QtCore.QSize(300, 40))
        self.usernameLE.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.usernameLE.setFont(font)
        self.usernameLE.setStyleSheet("#usernameLE{\n"
"background: transparent;\n"
"color:white;\n"
"border-bottom: 2px solid black;}\n"
"")
        self.usernameLE.setObjectName("usernameLE")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.register_nameLE.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Kayıt Ol</span></p></body></html>"))
        self.passWordLE_2.setPlaceholderText(_translate("Form", "Şifre "))
        self.officenameLE.setPlaceholderText(_translate("Form", "Baro Adı"))
        self.officeNO.setPlaceholderText(_translate("Form", "Baro Numarası"))
        self.Reg_pushButton.setText(_translate("Form", "Kayıt Ol"))
        self.usernameLE.setPlaceholderText(_translate("Form", "Kullanıcı Girişi"))
