# Form implementation generated from reading ui file 'trial.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class TrialWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1021, 811)
        Form.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(999, 789))
        self.widget.setStyleSheet("background-color: rgba(112, 112, 112);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(977, 767))
        self.widget_2.setStyleSheet("QLabel{\n"
"    font: 75 12pt \"Times New Roman\";\n"
"    background-color: rgb(255, 214, 97);\n"
"    border: 0px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.entry = QtWidgets.QLabel(parent=self.widget_2)
        self.entry.setGeometry(QtCore.QRect(-10, -10, 991, 191))
        self.entry.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.entry.setText("")
        self.entry.setObjectName("entry")
        self.return_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.return_2.setGeometry(QtCore.QRect(20, 20, 61, 51))
        self.return_2.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"image: url(:/image/return.png);")
        self.return_2.setText("")
        self.return_2.setObjectName("return_2")
        self.amblem = QtWidgets.QLabel(parent=self.widget_2)
        self.amblem.setGeometry(QtCore.QRect(90, 30, 101, 71))
        self.amblem.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"image: url(:/image/compliant.png);")
        self.amblem.setText("")
        self.amblem.setObjectName("amblem")
        self.ana_amblem = QtWidgets.QLabel(parent=self.widget_2)
        self.ana_amblem.setGeometry(QtCore.QRect(390, 10, 151, 91))
        self.ana_amblem.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"image: url(:/image/amblem.png);")
        self.ana_amblem.setText("")
        self.ana_amblem.setObjectName("ana_amblem")
        self.title = QtWidgets.QLabel(parent=self.widget_2)
        self.title.setGeometry(QtCore.QRect(324, 99, 281, 61))
        self.title.setStyleSheet("QLabel{\n"
"    font: 75 12pt \"Times New Roman\";\n"
"    background-color: rgb(255, 214, 97);\n"
"    border: 0px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.title.setObjectName("title")
        self.past_trial = QtWidgets.QListWidget(parent=self.widget_2)
        self.past_trial.setGeometry(QtCore.QRect(30, 330, 411, 391))
        self.past_trial.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.past_trial.setObjectName("past_trial")
        item = QtWidgets.QListWidgetItem()
        self.past_trial.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.past_trial.addItem(item)
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.widget_2)
        self.listWidget_2.setGeometry(QtCore.QRect(490, 330, 431, 391))
        self.listWidget_2.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"\n"
"")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.past_title = QtWidgets.QLabel(parent=self.widget_2)
        self.past_title.setGeometry(QtCore.QRect(70, 250, 341, 41))
        self.past_title.setStyleSheet("QLabel{\n"
"    font: 75 12pt \"Times New Roman\";\n"
"    background-color: rgb(255, 214, 97);\n"
"    border: 0px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.past_title.setObjectName("past_title")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(540, 249, 331, 41))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">AVAS DAVA DURUMLARI</span></p></body></html>"))
        __sortingEnabled = self.past_trial.isSortingEnabled()
        self.past_trial.setSortingEnabled(False)
        item = self.past_trial.item(1)
        item.setText(_translate("Form", "12.3.2002     BOŞANMA "))
        self.past_trial.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(1)
        item.setText(_translate("Form", "22.12.2023   İCRA"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.past_title.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">GEÇMİŞ DURUŞMALAR</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">GELECEK DURUŞMALAR</span></p></body></html>"))
